language: node_js

node_js:
  - "node"

cache: yarn

script:
  - yarn
  - yarn test
  - yarn build
  - xz bin/mp3dupes

deploy:
  - provider: pages
    skip-cleanup: true
    keep-history: true
    github-token: $GITHUB_TOKEN
    on:
      branch: master
    local-dir: results
  - provider: releases
    skip-cleanup: true
    keep-history: true
    github-token: $GITHUB_TOKEN
    on:
      tags
    file: bin/mp3dupes.xz
